# [general.import] = ["/home/sam/.config/alacritty/shared.toml"]

[font]
size = 16.0
normal = { family = "FantasqueSansM Nerd Font Mono", style = "Regular" }

[window]
dimensions = { columns = 0, lines = 0 }
dynamic_title = true
decorations = "None"
startup_mode = "Maximized"

[env]
TERM = "xterm-256color"

# [color.primary]
#     background =        '#282828'
#     foreground =        '#fbf1c7'
#     bright_foreground = '#f9f5d7'
#     dim_foreground =    '#f2e5bc'
# [color.cursor]
#     text =   "CellBackgrond"
#     cursor = "CellForeground"
# [color.vi_mode_cursor]
#     text =   "CellBackgrond"
#     cursor = "CellForeground"
# [color.selection]
#     text =       "CellBackgrond"
#     background = "CellForeground"
# [color.bright]
#     black =   '#928374'
#     red =     '#fb4934'
#     green =   '#b8bb26'
#     yellow =  '#fabd2f'
#     blue =    '#83a598'
#     magenta = '#d3869b'
#     cyan =    '#8ec07c'
#     white =   '#ebdbb2'
# [color.normal]
#     black =   '#282828'
#     red =     '#cc241d'
#     green =   '#98971a'
#     yellow =  '#d79921'
#     blue =    '#458588'
#     magenta = '#b16286'
#     cyan =    '#689d6a'
#     white =   '#a89984'
# [color.dim]
#     black =   '#32302f'
#     red =     '#9d0006'
#     green =   '#79740e'
#     yellow =  '#b57614'
#     blue =    '#076678'
#     magenta = '#8f3f71'
#     cyan =    '#427b58'
#     white =   '#928374'
